### PR TITLE
for use with frameworks with cocoapods V0.36 RC1

### PR DESCRIPTION
**Pull request by evermeer**
There is also a change needed for loading the nib files from a different bundle than the default

### CODE REVIEW

**Comment by evermeer** [comment]
See this answer about how to use bundles in a framework: 
http://stackoverflow.com/questions/24982848/loading-a-resource-e-g-storyboard-in-a-swift-framework

**Comment by evermeer** [comment]
Could you pleas give an update regarding this pull request?

**Comment by DZamataev** [comment]
Does this issue need further changes?

**Comment by evermeer** [comment]
I have put all 3 pull requests in my own fork. From there I can now directly use Chivy as a cocoa pod framework. My repo is at https://github.com/evermeer/Chivy

**Comment by DZamataev** [comment]
I've merged all your PRs and released Chivy version 0.4.0. You are welcome to use it instead of a fork.

**Comment by evermeer** [comment]
Great! thanks, will do that!

**Comment by evermeer** [comment]
Thanks! it's working, I added Chivy as a library to the demo app in https://github.com/evermeer/EVCloudKitDao When there is a URL in a chat conversation it will open a Chivy browser instead of going to Safari.

**Pull request merged**
